### ISSUE TITLE
Photo feature

### ISSUE THREAD

**Issue by hananeboussari** [wenzhiming/flutter_webview_pro#10]
la prise en charge des photos ne fonctionne pas dans l'application android.
J'ai autorisé la camera dans mon AndroidManifest.xml
Malgré cela j'ai toujours la même erreur ça ne fonctionne pas.

Que faut il faire ?

**Comment by wenzhiming** [comment]
Manifeste Android. Les permissions statiques XML ne s'appliquent qu'à Android 6. Les systèmes inférieurs à 0 sont valides parce qu'ils sont disponibles sur Android 6. L'autorisation de prendre des photos au - dessus de 0 doit être appliquée dynamiquement. C'est - à - dire que vous devez vous adapter aux permissions dynamiques.

-------
AndroidManifest. XML static permissions are only available for Android 6.0 Only systems below 0 are valid, because in Android 6 Photo permission above 0 must be applied dynamically. That is, you must adapt dynamic permissions.

**Comment by hananeboussari** [comment]
Comment puis-je m'adapté au permissions dynamique, puis je avoir une idée ?

**Comment by wenzhiming** [comment]
> 

Hello, take camera bug  is fixed on version 1.0.1
